// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// This file is a STUB for typecheck/CI. The real file is generated by
// `npx @tanstack/router-plugin` (run via `vite` / `vinxi dev`). The stub
// ensures `tsc --noEmit` passes without the generator on CI.

import type { AnyRoute } from "@tanstack/react-router";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const routeTree = {} as unknown as AnyRoute;

// Only kept so `src/app/router.tsx` can `import { routeTree } from "./routeTree.gen"`.
// When the Vite plugin runs, it overwrites this file with the real tree.
export const generatedRouteTree = routeTree;
