// Stub isomorphic TanStack Start Server Function for the Bun/Hono single-deployable.
// Real `@tanstack/react-start` would be generated by the Vite plugin and would RPC via
// `/_serverFn/{id}` on the client and execute directly on the server. For the MVP we
// are SSR-less and the web client calls these functions in-process through the same
// services layer that Hono uses (ADR-002 Principle 3 — Direct Calls).
//
// The builder API matches production: `createServerFn({method}).validator(Zod).handler(fn)`
// (and the no-validator form). Zod failures become `ValidationError` so the shared
// error contract (tanstack-start.md §4, §14) is identical to Hono. Errors are never
// swallowed — they propagate for the boundary to map (tanstack-start.md §19).
//
// Keeping this as a local module instead of an external `package.json` dependency means
// `bun.lock` stays in sync with CI's `--frozen-lockfile`. When the real TanStack Start
// toolchain is wired, delete this file and change the imports in `src/app/server-functions/*`
// to `import { createServerFn } from "@tanstack/react-start"`.

import { isZodError, validationErrorFromZod } from "@/lib/validation/parse";

type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

type HandlerArgs = {
  data: unknown;
  context?: unknown;
  signal?: AbortSignal | undefined;
};

type Validator =
  | { parse: (raw: unknown) => unknown; safeParse?: (raw: unknown) => unknown }
  | ((raw: unknown) => unknown | Promise<unknown>);

async function runValidator(raw: unknown, validator?: Validator): Promise<unknown> {
  if (!validator) return raw;
  try {
    const maybeParse = (validator as { parse?: unknown }).parse;
    if (typeof maybeParse === "function") {
      return (maybeParse as (x: unknown) => unknown).call(validator, raw);
    }
    if (typeof validator === "function") return await validator(raw);
    return raw;
  } catch (error) {
    if (isZodError(error)) throw validationErrorFromZod(error);
    throw error;
  }
}

export function createServerFn(opts?: { method?: Method }) {
  const method = opts?.method as Method | undefined;

  return {
    validator: (validator: Validator) => ({
      handler: (handler: (args: HandlerArgs) => unknown) =>
        (async (invocation?: {
          data?: unknown;
          context?: unknown;
          signal?: AbortSignal;
        }): Promise<unknown> => {
          const data = await runValidator(invocation?.data, validator);
          return handler({ data, context: invocation?.context, signal: invocation?.signal });
        }) as any,
    }),

    handler: (handler: (args: HandlerArgs) => unknown) =>
      (async (invocation?: {
        data?: unknown;
        context?: unknown;
        signal?: AbortSignal;
      }): Promise<unknown> => {
        return handler({
          data: invocation?.data,
          context: invocation?.context,
          signal: invocation?.signal,
        });
      }) as any,

    _method: method,
  };
}
