// Stub isomorphic TanStack Start Server Function for the Bun/Hono single-deployable.
// Real `@tanstack/react-start` would be generated by `vinxi` and would RPC via `/_serverFn/{id}`
// on the client and execute directly on the server. For the MVP we are SSR-less and the
// web client calls these functions in-process through the same services layer that Hono
// uses (ADR-002 Principle 3 — Direct Calls). The stub preserves the exact builder API
// (`createServerFn({method}).validator(Zod).handler(fn)` and the no-validator form) so
// switching to the real package is a single import-path change. Validation is performed
// with the same Zod schemas that the services and Hono routes use — i.e. Every Server
// Function Validates With Shared Zod — so the behavior matches production even though the
// RPC transport is replaced by a plain async function (no HTTP hop).
//
// Keeping this as a local module instead of an external `package.json` dependency means
// `bun.lock` stays in sync with CI's `--frozen-lockfile` without having to land a
// `bun.lock` rewrite in a GitHub-App push (which lacks `workflows:` scope for
// `.github/workflows/ci.yml`). When the real TanStack Start toolchain is wired, delete
// this file and change the imports in `src/app/server-functions/*` back to
// `import { createServerFn } from "@tanstack/react-start"` — the runtime contract is
// identical.

// Bun's `exactOptionalPropertyTypes` makes `{ signal?: AbortSignal }` incompatible
// with `signal: AbortSignal | undefined`, so the handler args must allow `undefined`
// explicitly. Using `any` for the validated payload keeps the inference identical to
// the real TanStack Start builder (where `data` is inferred from the validator) while
// letting `tsc --noEmit` pass without needing the external `@tanstack/react-start`
// package in `bun.lock`.
type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

type HandlerArgs = {
  data: any;
  context?: unknown;
  signal?: AbortSignal | undefined;
};

type Validator =
  | { parse: (raw: unknown) => unknown }
  | ((raw: unknown) => unknown | Promise<unknown>);

function runValidator(raw: unknown, validator?: Validator): unknown {
  if (!validator) return raw;
  const maybeParse = (validator as { parse?: unknown }).parse;
  if (typeof maybeParse === "function") {
    return (maybeParse as (x: unknown) => unknown).call(validator, raw);
  }
  if (typeof validator === "function") return (validator as (x: unknown) => unknown)(raw);
  return raw;
}

export function createServerFn(opts?: { method?: Method }) {
  const method = opts?.method as Method | undefined;

  return {
    validator: (validator: Validator) => ({
      handler: (handler: (args: HandlerArgs) => any) =>
        (async (invocation?: {
          data?: unknown;
          context?: unknown;
          signal?: AbortSignal;
        }): Promise<any> => {
          const raw = invocation?.data;
          const data = await runValidator(raw, validator);
          return handler({ data, context: invocation?.context, signal: invocation?.signal });
        }) as any,
    }),

    handler: (handler: (args: HandlerArgs) => any) =>
      (async (invocation?: {
        data?: unknown;
        context?: unknown;
        signal?: AbortSignal;
      }): Promise<any> => {
        const data = invocation?.data;
        return handler({ data, context: invocation?.context, signal: invocation?.signal });
      }) as any,

    _method: method,
  };
}
